### ISSUE TITLE
Spike: Evaluate Container Runtime Options

### ISSUE THREAD

**Issue by danielsomerfield** [somesyd/single-budget#4]
Options to evaluate:
* EKS (kubernetes)
* ECS ("classic" with EC2 launch type)
* Fargate (ECS with Fargate launch type)

Evaluation criteria
* Suitability to workloads
* Cost
* Ease of use

Resources
* https://aws.amazon.com/getting-started/decision-guides/containers-on-aws-how-to-choose/
* https://docs.aws.amazon.com/AmazonECS/latest/developerguide/launch_types.html
* https://docs.aws.amazon.com/AmazonECS/latest/developerguide/AWS_Fargate.html

Time box: 4 hours
Outcome: presentation of 10 minutes or less on findings, including a recommendation of which one to use.

**Comment by somesyd** [comment]
Based on the evaluation criteria, we have decided to use ECS with the Fargate launch type.

Suitability to workloads
- Since the workload will likely be small (run in timed batches), Fargate would be a good option

Cost
- Small batches should be cheaper to run with ECS than EKS
- Fargate is serverless, so if we only run it when needed, there will only be small charges for CPU, memory, and ephemeral storage

Ease of Use
- Considering the steep learning curve of EKS, ECS will take less ramp-up time
- Fargate will be easier than EC2 because there's no need to provision, configure, or scale VM clusters
